### ISSUE TITLE
Update solution to Visual Studio 2017 and Target .Net Standard 1.6

### ISSUE THREAD

**Issue by louisfischer** [cake-contrib/Cake.Http#23]
Update solution to Visual Studio 2017 and Target the .Net Standard 1.5. 
Targeting  .NET Standard 1.5 will give the greatest range of reusability between the different frameworks.

https://docs.microsoft.com/en-us/dotnet/standard/library

![image](https://user-images.githubusercontent.com/1905010/27006065-5520e420-4de0-11e7-9221-a6070b9302a4.png)

**Comment by gep13** [comment]
@louisfischer so Cake.Recipe now has basic support for VS 2017 projects. Let me know if you run into any issues.

**Comment by louisfischer** [comment]
@gep13 Sure no problem. I read on gitter that v.20.0 will have migrated to VS2017 and the MSBuild tools. I was going to get this one ready after the core Cake project is done migrating to VS2017

**Comment by gep13** [comment]
@louisfischer so for the next release, your addin will continue to function as is.  However, upgrading and targetting both .Net and netstandard is definitely something that we are starting to encourage 👍

**Comment by louisfischer** [comment]
@phenixdotnet Thank you for getting the majority of the project converted over to .NetStandard 1.6. 
There are only a couple of minor changes I would like to make before publishing the nuget package
