### ISSUE TITLE
Unable to add body to Delete requests

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Http#29]
@louisfischer last night, I was adding a new piece of functionality to Cake.Wyam.Recipe where I wanted to send a DELETE request to the Cloudflare API.  This request needed to have the standard headers, but it also needed to contain a body.

The request in question is this one:

https://api.cloudflare.com/#zone-purge-all-files

My immediate thought was to use Cake.Http, but it looks like there isn't an alias that would let me do this, unless I am mistaken.

Can I suggest adding a generic alias around `HttpClient.SendAsync` where the consumer constructs everything that is required, as I ended up doing here:

https://github.com/cake-contrib/Cake.Wyam.Recipe/blob/develop/Cake.Wyam.Recipe/Content/wyam.cake#L103

**Comment by louisfischer** [comment]
Added Generic Send method from pull request #30
