### ISSUE TITLE
Convert this repo to use Cake.Recipe

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Http#3]
@louisfischer I am pretty much at the point where my not so secret project, Cake.Recipe, is ready to be rolled out.

Would you be interested in me adding it to this repository?

The benefits would be...

- a single place to control all the builds in the cake-contrib organisation
- access to notifications on twitter and gitter when new releases are available

Things that Cake.Recipe already does:

- Version with GitVersion
- Build
- Compile
- Run Unit Tests
- Submit results to coveralls.io
- NuGet Package everything
- Upload all artifacts to AppVeyor
- Runs DupFinder
- Runs InspectCode
- Handles publishing to both MyGet and NuGet (for interim releases)
- Runs GitLink, meaning that addin code is debuggable doing debug session in visual studio when debugging build.cake
- Documentation Website generation using Wyam

Probably other stuff that I have forgotten.

The main thing being, if we add something to Cake.Recipe, then all projects that are already using Cake.Recipe should be able to immediately take advantage of it.

Thoughts?  If you were interested, would you be happy to have me make the changes directly to repo, or would you prefer it as a PR?

**Comment by louisfischer** [comment]
Very interested...PR would be great... I already saw some of the notification s in the gutter chat room.

**Comment by gep13** [comment]
@louisfischer so, I believe the work for this repository has now been completed.  The only thing that is left to do is to publish the 0.2.0 release, and the rest should be taken care of, including pushing out the nuget package to NuGet.org.

Are you happy for me to proceed with this?

Also, another question...

Cake.Recipe works best when using GitFlow (which is what we use on the main Cake repository).  Currently you only have a master branch.  Would you be ok with me adding another branch called develop, and making this the default branch for this repository?  And all future work will be done on this branch, before merging into master?

**Comment by louisfischer** [comment]
That will work for me. I was just using GitHub flow but Gitflow works for me as well. Any future work will be done on feature branches and merged into develop instead of master. Thanks again for all your work on this.

**Comment by gep13** [comment]
Okay, this is ready to go....

Running the final build now.
