### ISSUE TITLE
The type or namespace name 'Http' does not exist in the namespace 'System.Net'

### ISSUE THREAD

**Issue by DixonDs** [cake-contrib/Cake.Http#31]
It started to fail with this error after update to 0.2.8

**Comment by policarpo** [comment]
Try replacing `#addin "Cake.Http"` with `#addin "nuget:?package=Cake.Http&version=0.2.6"`

**Comment by DixonDs** [comment]
@policarpo Thanks, that's what we did before filing this issue :)

**Comment by bfiricel** [comment]
The issue occurs in 0.2.9 also

**Comment by louisfischer** [comment]
Sorry needed to add nuspec references and Cake namespace imports to Aliases

**Comment by bfiricel** [comment]
I'm afraid 0.2.10 did not fix this, the same error occurs.

**Comment by bfiricel** [comment]
0.2.11 works fine! 👍

**Comment by louisfischer** [comment]
Seems i needed to change the System.Net.Http to copy to local and add the reference to the nuspec file.
