### ISSUE TITLE
A better way to send multiple values through encoded form

### ISSUE THREAD

**Issue by johnnyasantoss** [cake-contrib/Cake.Http#4]
For now `Cake.Http` uses a `IDicitionary<string, string>` to send a POST using `HttpSettings.SetFormUrlEncodedRequestBody()` method.

I would suggest to use a `IEnumerable<KeyValuePair<string, string>>` because of the multiple valued "inputs" that a encoded form can receive.

Eg.

[![Example](http://image.prntscr.com/image/89f8ddeea0ac41dc8aac6123f8540f9a.png)](http://codepen.io/anon/pen/XpBrqq)

**Comment by louisfischer** [comment]
This is possible. PR is always welcome

**Comment by johnnyasantoss** [comment]
Hello!

Sorry for the delay. I've been really busy lately :(

Here's your PR #7  :smile:

**Comment by louisfischer** [comment]
Thanks for the PR and added to the 0.2.1 release.
