### ISSUE TITLE
Support for Client Certificate

### ISSUE THREAD

**Issue by pardahlman** [cake-contrib/Cake.Http#41]
Hello, thanks for a top notch cake extension 👌 .

I have an application that requires client certificate when calling its RESTful API. It looks like this addin does not have support for this scenario at the moment. On the other hand, it shouldn't be that difficult to expose client certificate in `HttpSettings` and then set it the handler's `ClientCertificates`.

Let me know what you think - I'd be more than happy to submit a PR if you think it's a good idea.

Keep up the good work!

**Comment by louisfischer** [comment]
Sounds like a good addition to the plugin...If you want to submit a PR that would be great

**Comment by pardahlman** [comment]
Coolio! I'll see what I can do later this week or next week :tada:

**Comment by pardahlman** [comment]
Hello again, I've started to look at this and I've run into a problem: The [`HttpClientHandler`](https://docs.microsoft.com/sv-se/dotnet/api/system.net.http.httpclienthandler?view=netframework-4.7) does not contain the `ClientCertificates` property (it was introduced in 4.7.1). Earlier version of .NET Framework have to use [`WebRequestHandler`](https://docs.microsoft.com/sv-se/dotnet/api/system.net.http.webrequesthandler?view=netframework-4.6), which has supported this since 4.5.

There is no problem using the `WebRequestHandler`, but the `CakeHttpClientHandler` can no longer inherit from `DelegatingHandler` as the property `InnerHandler` is of type `HttpMessageHandler`. I just wanted to check if you are OK with this before I spend more time on this.

Cheers!

**Comment by louisfischer** [comment]
@pardahlman  Thanks for the contribution....
