### ISSUE TITLE
Can we get the response status code?

### ISSUE THREAD

**Issue by raghav710** [cake-contrib/Cake.Http#50]
We have a scenario where we have a task that pings a server in order to check if its up before running other tasks. Examining the status code would be useful in such a case.

Do we have  a way to get back an object with the response string _and_ status code? If not I'd be happy to submit a PR that does the same. I'm worried about that being a breaking change to the API though. Any help on this is appreciated.

**Comment by louisfischer** [comment]
Fixed with PR #66. You now have the ability to use HttpSend with a Raw HttpRequestMessage recieve and HttpResponseMessage
