### ISSUE TITLE
The name 'HttpPost' does not exist in the current context

### ISSUE THREAD

**Issue by mhoopertr** [cake-contrib/Cake.Http#56]
I don't know if it is intentional or not but https://www.nuget.org/packages/Cake.Http/0.6.0 causes a problem with our builds.  Pinning to 0.5.0 resolved my issue & I've not had a chance to look at the code to see what could be causing the issue - if I get time I may post an update

**Comment by mhoopertr** [comment]
Looking at recent changes, this is the only change I can see which may have caused the problem:

`<PackageReference Include="System.Net.Http" Version="4.3.4" />`

**Comment by louisfischer** [comment]
Thank for reporting the issue. It will be resolved shortly in the next push to nuget.
