### ISSUE TITLE
Update to .NetStandard 2.1 and .NET Core 3.0

### ISSUE THREAD

**Issue by louisfischer** [cake-contrib/Cake.Http#59]
Update .NetStandard 2.1 and .NET Core 3.0 to take advantage of some of the new features of .NET Core (e.g. - New JSON Serializer_

## Expected Behavior
Behavior would stay the same, only update plugin dependencies.

## Current Behavior
No behavioral changes expected.

**Comment by pascalberger** [comment]
@louisfischer You sure you want to do this? This will break your addin for all people which are running Cake under .NET Framework, Mono or .NET Core < 3.0.

Current [guideline](https://github.com/cake-contrib/Home/blob/master/Guidelines.md#framework) is still to multi-target .NET Framework 4.6.1 and .NET Standard 2.0 for maximum compatibility with all scenarios where Cake itself can run.

**Comment by louisfischer** [comment]
@pascalberger That makes sense. This plugin has relatively high downloads and not a lot of issues reported for it. The last thing I want to do is break it. I will mark this one as a future enhancement.
