### ISSUE TITLE
HttpPost without a body setted throws error

### ISSUE THREAD

**Issue by DarylSerrano** [cake-contrib/Cake.Http#60]
When using the examples in the [documentation](https://cakebuild.net/api/Cake.Http/HttpClientAliases/DE5A475F), the alias HttpPost without providing a the body throws an error:
```
Error: One or more errors occurred.
        Value cannot be null.
Parameter name: content
```

## Expected Behavior
Be able to send a POST without a body setted, or by default set an empty body

## Current Behavior
Throws an error:
```
Error: One or more errors occurred.
        Value cannot be null.
Parameter name: content
```

## Possible Solution
Updating the examples on the documentation or providing information that setting a Body is obligatory when making a POST or make it posible to just send an empty body.

## Steps to Reproduce (for bugs)
I have used the example code in the [Documentation](https://cakebuild.net/api/Cake.Http/HttpClientAliases/DE5A475F)
```
Task("Manual Test")
.Does(() => {
        string responseBody = HttpPost("https://www.google.com");
});
```
I also get the same error code on the example code in this [page](https://cakebuild.net/api/Cake.Http/HttpClientAliases/59D2F2C3)

## Context
Make a POST without providing settings or a body.

## Your Environment
* Cake version 0.37.0
* Cake.Http version 0.7.0
* Windows 10 x64
* PowerShell 5.1.17763.1007

**Comment by louisfischer** [comment]
Fixed with PR #66. You now have the ability to use HttpSend with a Raw HttpRequestMessage recieve and HttpResponseMessage
