### ISSUE TITLE
Add SetRequestBody overload accepting an object

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Http#9]
It would be nice if there would be an overload of the `SetRequestBody` method accepting an object which internally serializes the object to JSON.

**Comment by louisfischer** [comment]
@pascalberger cake.http 2.2 has been released with the requested feature

**Comment by pascalberger** [comment]
@louisfischer Thanks! You might want to use ILMerge or Fody Costura though to make this addin compatible with others using a different version of JSON.NET.

**Comment by pascalberger** [comment]
@louisfischer FYI, I just saw that you missed to set the milestone for this issue and therefore it is also not mentioned in the release notes.
